-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPdGByj2XL0Td14vk
X2Q1nuPHHR1zJltJ2sry6pp3yk2gCgYIKoZIzj0DAQehRANCAATgjjNzr2dXBzaK
o21AN7YgEc1b8kyWKZcguO0Z6WzrysDk+nSlCDsU/iTkeTfAwR/DgByfKMMMRaGg
cTEJLLhJ
-----END PRIVATE KEY-----